/** Curated demo reference data. Approximate nutrition for demonstration only. */

const FOODS = [
  ["Vegetable Poha", "grains", "breakfast", "1 bowl (180 g)", 250, 5.0, 45.0, 6.0, 3.5, true, true, "peanut", "Flattened rice with peas, onion and peanuts"],
  ["Masala Oats", "grains", "breakfast", "1 bowl (200 g)", 220, 8.0, 34.0, 5.0, 6.0, true, true, "gluten", "Savoury oats with mixed vegetables"],
  ["Idli with Sambar", "grains", "breakfast", "3 idli + sambar", 290, 10.0, 52.0, 3.5, 5.0, true, true, "", "Steamed rice cakes with lentil stew"],
  ["Moong Dal Chilla", "protein", "breakfast", "2 pieces", 260, 14.0, 32.0, 7.0, 6.0, true, true, "", "Savoury lentil pancakes"],
  ["Besan Chilla", "protein", "breakfast", "2 pieces", 240, 12.0, 28.0, 8.0, 5.0, true, true, "", "Gram flour pancakes with vegetables"],
  ["Boiled Eggs", "protein", "breakfast", "2 eggs", 155, 13.0, 1.1, 11.0, 0.0, false, false, "egg", "Simple protein-dense breakfast"],
  ["Egg White Omelette", "protein", "breakfast", "3 whites + veg", 120, 18.0, 4.0, 2.0, 1.0, false, false, "egg", "High protein, low fat omelette"],
  ["Greek Yogurt with Berries", "dairy", "breakfast", "200 g", 180, 17.0, 18.0, 4.0, 2.5, true, false, "milk", "High protein yogurt bowl"],
  ["Banana Peanut Butter Toast", "grains", "breakfast", "2 slices", 330, 10.0, 46.0, 12.0, 5.0, true, true, "peanut,gluten", "Wholegrain toast with banana"],
  ["Upma", "grains", "breakfast", "1 bowl (180 g)", 230, 6.0, 38.0, 6.5, 3.0, true, true, "gluten", "Semolina cooked with vegetables"],
  ["Sprouts Salad", "vegetables", "breakfast", "1 bowl (150 g)", 160, 12.0, 24.0, 1.5, 7.0, true, true, "", "Moong sprouts with lemon and onion"],
  ["Soy Milk Smoothie", "beverages", "breakfast", "1 glass (300 ml)", 190, 9.0, 27.0, 5.0, 3.0, true, true, "soy", "Soy milk blended with banana and oats"],
  ["Paneer Bhurji", "dairy", "breakfast", "150 g", 300, 18.0, 8.0, 22.0, 2.0, true, false, "milk", "Scrambled cottage cheese with spices"],
  ["Ragi Porridge", "grains", "breakfast", "1 bowl (200 g)", 210, 6.0, 40.0, 3.0, 5.5, true, true, "", "Finger millet porridge"],
  ["Dal Tadka", "protein", "lunch", "1 bowl (200 g)", 210, 12.0, 28.0, 6.0, 7.0, true, true, "", "Yellow lentils tempered with spices"],
  ["Rajma Curry", "protein", "lunch", "1 bowl (200 g)", 245, 13.0, 36.0, 5.0, 10.0, true, true, "", "Kidney beans in tomato gravy"],
  ["Chole (Chickpea Curry)", "protein", "lunch", "1 bowl (200 g)", 270, 13.0, 38.0, 8.0, 10.5, true, true, "", "Spiced chickpea curry"],
  ["Brown Rice", "grains", "lunch", "1 cup cooked (160 g)", 215, 5.0, 45.0, 1.8, 3.5, true, true, "", "Wholegrain rice"],
  ["Roti (Whole Wheat)", "grains", "lunch", "2 rotis", 210, 7.0, 40.0, 3.0, 5.0, true, true, "gluten", "Wholewheat flatbread"],
  ["Grilled Chicken Breast", "protein", "lunch", "150 g", 250, 45.0, 0.0, 6.0, 0.0, false, false, "", "Lean poultry protein"],
  ["Fish Curry", "protein", "lunch", "150 g", 230, 28.0, 6.0, 10.0, 1.0, false, false, "fish", "Coastal-style fish curry"],
  ["Paneer Tikka", "dairy", "lunch", "150 g", 300, 20.0, 9.0, 21.0, 1.5, true, false, "milk", "Grilled spiced cottage cheese"],
  ["Tofu Stir Fry", "protein", "lunch", "180 g", 240, 20.0, 12.0, 13.0, 3.5, true, true, "soy", "Tofu with mixed vegetables"],
  ["Mixed Vegetable Sabzi", "vegetables", "lunch", "1 bowl (180 g)", 140, 4.0, 18.0, 6.0, 6.0, true, true, "", "Seasonal vegetables lightly cooked"],
  ["Quinoa Salad Bowl", "grains", "lunch", "1 bowl (220 g)", 290, 11.0, 42.0, 9.0, 7.0, true, true, "", "Quinoa with beans and vegetables"],
  ["Curd (Plain Yogurt)", "dairy", "lunch", "150 g", 100, 6.0, 8.0, 4.0, 0.0, true, false, "milk", "Plain set yogurt"],
  ["Rajgira Khichdi", "grains", "lunch", "1 bowl (200 g)", 260, 8.0, 42.0, 7.0, 4.0, true, true, "", "Amaranth and lentil one-pot meal"],
  ["Egg Curry", "protein", "lunch", "2 eggs in gravy", 280, 16.0, 10.0, 20.0, 2.0, false, false, "egg", "Eggs in onion-tomato gravy"],
  ["Palak Dal", "protein", "dinner", "1 bowl (200 g)", 195, 12.0, 24.0, 5.0, 7.5, true, true, "", "Lentils cooked with spinach"],
  ["Vegetable Khichdi", "grains", "dinner", "1 bowl (220 g)", 250, 9.0, 44.0, 4.0, 5.5, true, true, "", "Rice and lentils with vegetables"],
  ["Grilled Fish", "protein", "dinner", "150 g", 210, 30.0, 0.0, 9.0, 0.0, false, false, "fish", "Lightly spiced grilled fish"],
  ["Chicken Stew", "protein", "dinner", "1 bowl (220 g)", 260, 28.0, 12.0, 11.0, 2.0, false, false, "", "Light chicken and vegetable stew"],
  ["Tofu Bhurji", "protein", "dinner", "160 g", 215, 18.0, 9.0, 12.0, 3.0, true, true, "soy", "Scrambled tofu with spices"],
  ["Lauki Sabzi", "vegetables", "dinner", "1 bowl (180 g)", 110, 3.0, 14.0, 5.0, 4.5, true, true, "", "Bottle gourd cooked light"],
  ["Jowar Roti", "grains", "dinner", "2 rotis", 180, 5.0, 38.0, 1.5, 5.0, true, true, "", "Sorghum flatbread, gluten free"],
  ["Mixed Bean Soup", "protein", "dinner", "1 bowl (250 ml)", 190, 11.0, 28.0, 3.0, 8.0, true, true, "", "Warm bean and vegetable soup"],
  ["Grilled Paneer Salad", "dairy", "dinner", "180 g", 265, 19.0, 10.0, 17.0, 3.0, true, false, "milk", "Paneer over greens"],
  ["Vegetable Soup", "vegetables", "dinner", "1 bowl (250 ml)", 90, 3.0, 14.0, 2.0, 4.0, true, true, "", "Clear vegetable soup"],
  ["Chickpea Salad", "protein", "dinner", "1 bowl (200 g)", 230, 11.0, 32.0, 6.0, 9.0, true, true, "", "Chickpeas with cucumber and lemon"],
  ["Methi Thepla", "grains", "dinner", "2 pieces", 220, 6.0, 34.0, 7.0, 4.5, true, true, "gluten", "Fenugreek flatbread"],
  ["Baked Sweet Potato", "vegetables", "dinner", "200 g", 180, 4.0, 41.0, 0.3, 6.0, true, true, "", "Naturally sweet, high fibre"],
  ["Prawn Stir Fry", "protein", "dinner", "150 g", 200, 26.0, 8.0, 7.0, 1.5, false, false, "shellfish", "Prawns with peppers"],
  ["Apple", "fruits", "snack", "1 medium (180 g)", 95, 0.5, 25.0, 0.3, 4.4, true, true, "", "Portable high-fibre fruit"],
  ["Banana", "fruits", "snack", "1 medium (120 g)", 105, 1.3, 27.0, 0.4, 3.1, true, true, "", "Quick pre-workout carbohydrate"],
  ["Orange", "fruits", "snack", "1 medium (150 g)", 70, 1.2, 18.0, 0.2, 3.4, true, true, "", "Hydrating citrus fruit"],
  ["Papaya Cubes", "fruits", "snack", "1 bowl (150 g)", 60, 0.9, 15.0, 0.2, 2.5, true, true, "", "Light, water-rich fruit"],
  ["Watermelon Slices", "fruits", "snack", "200 g", 60, 1.2, 15.0, 0.3, 0.8, true, true, "", "Very high water content"],
  ["Roasted Chana", "protein", "snack", "40 g", 150, 8.0, 22.0, 2.5, 6.0, true, true, "", "Crunchy roasted chickpeas"],
  ["Almonds", "protein", "snack", "20 g (15 nuts)", 120, 4.4, 4.5, 10.5, 2.5, true, true, "tree_nut", "Healthy fats and vitamin E"],
  ["Walnuts", "protein", "snack", "20 g", 130, 3.0, 2.8, 13.0, 1.4, true, true, "tree_nut", "Source of omega-3 fats"],
  ["Buttermilk (Chaas)", "beverages", "snack", "1 glass (250 ml)", 70, 3.5, 6.0, 3.0, 0.0, true, false, "milk", "Cooling probiotic drink"],
  ["Coconut Water", "beverages", "snack", "1 glass (250 ml)", 45, 1.7, 9.0, 0.2, 0.0, true, true, "", "Natural electrolyte drink"],
  ["Lemon Water", "beverages", "snack", "1 glass (250 ml)", 15, 0.2, 4.0, 0.0, 0.2, true, true, "", "Simple hydration option"],
  ["Cucumber Sticks", "vegetables", "snack", "150 g", 25, 1.0, 5.0, 0.2, 1.0, true, true, "", "Very low calorie, hydrating"],
  ["Boiled Corn", "vegetables", "snack", "1 cup (160 g)", 130, 5.0, 29.0, 1.5, 3.5, true, true, "", "Warm high-fibre snack"],
  ["Peanut Chikki", "snacks", "snack", "30 g", 150, 5.0, 17.0, 7.5, 2.0, true, true, "peanut", "Traditional peanut brittle"],
  ["Sprouted Moong Chaat", "protein", "snack", "120 g", 130, 9.0, 20.0, 1.0, 6.0, true, true, "", "Tangy sprout salad"],
  ["Makhana (Fox Nuts)", "snacks", "snack", "30 g", 110, 3.5, 22.0, 0.5, 2.0, true, true, "", "Light roasted puffed seeds"],
];

const ACTIVITIES = [
  ["Brisk Walk", "walking", 30, 150, "easy", "low", "Comfortable pace, able to hold a conversation"],
  ["Evening Stroll", "walking", 20, 80, "easy", "low", "Gentle walk to wind down"],
  ["Recovery Walk", "walking", 25, 95, "easy", "low", "Very light movement on a rest day"],
  ["Stair Climbing", "cardio", 15, 130, "moderate", "high", "Short, intense bursts of stair work"],
  ["Light Jogging", "jogging", 25, 230, "moderate", "moderate", "Easy continuous jog"],
  ["Interval Running", "jogging", 30, 350, "hard", "high", "Alternating fast and easy running"],
  ["Cycling (Flat)", "cycling", 40, 300, "moderate", "moderate", "Steady outdoor or stationary cycling"],
  ["Cycling Intervals", "cycling", 30, 340, "hard", "high", "High-resistance cycling intervals"],
  ["Bodyweight Strength Circuit", "strength training", 30, 200, "moderate", "moderate", "Squats, push-ups, lunges, planks"],
  ["Dumbbell Full Body", "strength training", 45, 280, "hard", "high", "Compound lifts with dumbbells"],
  ["Resistance Band Workout", "strength training", 25, 150, "easy", "moderate", "Joint-friendly resistance work"],
  ["Core Strength Session", "strength training", 20, 120, "moderate", "moderate", "Planks, dead bugs, bird dogs"],
  ["HIIT Circuit", "cardio", 20, 280, "hard", "high", "Short work intervals with brief rest"],
  ["Low Impact Cardio", "cardio", 30, 180, "easy", "moderate", "Marching, step-touch, gentle movement"],
  ["Dance Cardio", "cardio", 30, 240, "moderate", "moderate", "Fun, music-led cardio"],
  ["Hatha Yoga", "yoga", 40, 140, "easy", "low", "Slow held postures with breathing"],
  ["Power Yoga", "yoga", 40, 250, "moderate", "moderate", "Faster flowing yoga sequence"],
  ["Sun Salutations", "yoga", 15, 90, "easy", "moderate", "Rounds of Surya Namaskar"],
  ["Full Body Stretch", "stretching", 15, 50, "easy", "low", "Head-to-toe static stretching"],
  ["Evening Wind-Down Stretch", "stretching", 12, 40, "easy", "low", "Gentle stretches before bed"],
  ["Hip and Shoulder Mobility", "mobility", 15, 60, "easy", "low", "Mobility drills for desk workers"],
  ["Spine Mobility Flow", "mobility", 12, 55, "easy", "low", "Cat-cow, thoracic rotations"],
  ["Desk Activity Break", "activity break", 5, 20, "easy", "low", "Stand, stretch and walk for five minutes"],
  ["Hourly Movement Break", "activity break", 3, 12, "easy", "low", "Short reset between work blocks"],
  ["Swimming (Steady)", "cardio", 30, 290, "moderate", "moderate", "Continuous easy laps"],
  ["Skipping Rope", "cardio", 15, 200, "hard", "high", "High intensity, high impact"],
  ["Hill Walk", "walking", 35, 230, "moderate", "moderate", "Walking on an incline"],
  ["Pilates Basics", "mobility", 30, 150, "moderate", "moderate", "Controlled core-focused movement"],
];

module.exports = { FOODS, ACTIVITIES };
