import { useState } from 'react'
import Card from '../components/Card'
import Disclaimer from '../components/Disclaimer'
import RangePicker from '../components/RangePicker'
import { EmptyState, ErrorState, Loading } from '../components/States'
import { useToast } from '../context/ToastContext'
import useApi from '../hooks/useApi'
import { api } from '../services/api'

const today = () => new Date().toISOString().slice(0, 10)
const BLANK = {
  date: today(), weight: '', water: '', sleep: '', steps: '',
  exercise_minutes: '', calories: '', mood: '3', stress: '3', notes: '',
}

export default function Logs() {
  const toast = useToast()
  const [range, setRange] = useState(7)
  const [form, setForm] = useState(BLANK)
  const [busy, setBusy] = useState(false)
  const { data, error, loading, reload } = useApi(() => api.listLogs(range), [range])
  const tips = useApi(() => api.wellness(), [])

  const change = (e) => setForm({ ...form, [e.target.name]: e.target.value })

  async function submit(e) {
    e.preventDefault()
    setBusy(true)
    try {
      const payload = Object.fromEntries(
        Object.entries(form).filter(([, v]) => v !== ''))
      await api.createLog(payload)
      toast.success('Log saved.')
      setForm({ ...BLANK, date: form.date })
      reload()
      tips.reload()
    } catch (err) {
      toast.error(err.message)
    } finally {
      setBusy(false)
    }
  }

  async function remove(id) {
    try {
      await api.deleteLog(id)
      toast.success('Log deleted.')
      reload()
    } catch (err) {
      toast.error(err.message)
    }
  }

  const field = (name, label, props = {}) => (
    <div className="field">
      <label htmlFor={name}>{label}</label>
      <input id={name} name={name} value={form[name]} onChange={change} {...props} />
    </div>
  )

  return (
    <>
      <h1>Wellness log</h1>

      <Card title="Record a day" sub="Saving the same date again updates that entry.">
        <form onSubmit={submit} noValidate>
          <div className="grid cols-4">
            {field('date', 'Date', { type: 'date', max: today(), required: true })}
            {field('weight', 'Weight (kg)', { type: 'number', step: '0.1', min: 25, max: 300 })}
            {field('water', 'Water (ml)', { type: 'number', min: 0, max: 10000 })}
            {field('sleep', 'Sleep (hours)', { type: 'number', step: '0.1', min: 0, max: 24 })}
            {field('steps', 'Steps', { type: 'number', min: 0, max: 100000 })}
            {field('exercise_minutes', 'Exercise (minutes)',
              { type: 'number', min: 0, max: 1440 })}
            {field('calories', 'Calories eaten', { type: 'number', min: 0, max: 10000 })}
            <div className="field">
              <label htmlFor="mood">Mood (1 low – 5 high)</label>
              <input id="mood" name="mood" type="range" min="1" max="5"
                     value={form.mood} onChange={change} />
              <div className="hint">Currently {form.mood}</div>
            </div>
            <div className="field">
              <label htmlFor="stress">Stress (1 low – 5 high)</label>
              <input id="stress" name="stress" type="range" min="1" max="5"
                     value={form.stress} onChange={change} />
              <div className="hint">Currently {form.stress}</div>
            </div>
          </div>
          <button type="submit" disabled={busy}>{busy ? 'Saving…' : 'Save log'}</button>
        </form>
      </Card>

      <Card title="Suggestions from your logs">
        {tips.loading ? <Loading label="Reading your logs" />
          : tips.error ? <ErrorState error={tips.error} onRetry={tips.reload} />
          : (
            <>
              <ul style={{ paddingLeft: 18, margin: 0 }}>
                {tips.data.tips.map((tip) => (
                  <li key={tip.code} style={{ marginBottom: 10 }}>
                    {tip.message}
                    <div style={{ fontSize: '.82rem', color: 'var(--ink-soft)' }}>
                      {tip.reason}
                    </div>
                  </li>
                ))}
              </ul>
              {tips.data.source === 'rules_only' && (
                <p className="hint" style={{ marginTop: 12 }}>
                  Generated by the rule engine (the model is currently off).
                </p>
              )}
            </>
          )}
      </Card>

      <Card title="History" actions={<RangePicker value={range} onChange={setRange} />}>
        {loading ? <Loading label="Loading your logs" />
          : error ? <ErrorState error={error} onRetry={reload} />
          : data.logs.length === 0
            ? <EmptyState>Nothing recorded in the last {range} days yet.</EmptyState>
            : (
              <div style={{ overflowX: 'auto' }}>
                <table>
                  <thead>
                    <tr>
                      <th>Date</th><th className="num">Weight</th><th className="num">Water</th>
                      <th className="num">Sleep</th><th className="num">Steps</th>
                      <th className="num">Exercise</th><th className="num">Mood</th>
                      <th><span className="sr-only">Actions</span></th>
                    </tr>
                  </thead>
                  <tbody>
                    {data.logs.map((log) => (
                      <tr key={log.log_id}>
                        <td>{log.date}</td>
                        <td className="num">{log.weight ?? '—'}</td>
                        <td className="num">{log.water ?? '—'}</td>
                        <td className="num">{log.sleep ?? '—'}</td>
                        <td className="num">{log.steps ?? '—'}</td>
                        <td className="num">{log.exercise_minutes ?? '—'}</td>
                        <td className="num">{log.mood ?? '—'}</td>
                        <td>
                          <button className="danger"
                                  style={{ padding: '3px 10px', fontSize: '.8rem' }}
                                  onClick={() => remove(log.log_id)}
                                  aria-label={`Delete the log for ${log.date}`}>
                            Delete
                          </button>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
      </Card>

      <Disclaimer />
    </>
  )
}
